// src/utils/printChildReport.js
// دالة توليد تقرير HTML قابل للطباعة عن الطفل

export const printChildReport = ({
  child,
  growthRecords   = [],
  medicalEvents   = [],
  medicalFiles    = [],
  sleepRecords    = [],
  feedingRecords  = [],
  appointments    = [],
  dailySummary    = [],   // مصفوفة من child_daily_health_summary
  healthSummary   = null, // ملخص اليوم الحالي
  isAr            = true,
  doctorMode      = false, // إذا كان الطبيب هو من يطبع
  doctorName      = "",
}) => {
  const t = isAr
    ? {
        title:         "تقرير صحة الطفل",
        generatedBy:   "صادر عن: منصة رحلة الأمومة",
        printDate:     "تاريخ التقرير:",
        childInfo:     "معلومات الطفل",
        name:          "الاسم",
        birthDate:     "تاريخ الميلاد",
        age:           "العمر",
        gender:        "الجنس",
        bloodType:     "فصيلة الدم",
        feeding:       "طريقة التغذية",
        milestone:     "المرحلة العمرية",
        growthTitle:   "سجل النمو",
        date:          "التاريخ",
        weight:        "الوزن (كغ)",
        height:        "الطول (سم)",
        head:          "محيط الرأس (سم)",
        medicalTitle:  "السجل الطبي",
        type:          "النوع",
        event:         "الحدث",
        desc:          "الوصف",
        sleepTitle:    "سجل النوم (7 أيام)",
        start:         "البداية",
        end:           "النهاية",
        duration:      "المدة",
        quality:       "الجودة",
        feedingTitle:  "سجل التغذية (30 يوم)",
        time:          "الوقت",
        method:        "الطريقة",
        ml:            "الكمية (مل)",
        min:           "المدة (د)",
        apptTitle:     "المواعيد الطبية",
        doctor:        "الطبيب",
        apptType:      "نوع الموعد",
        status:        "الحالة",
        summaryTitle:  "الملخص اليومي (آخر 30 يوم)",
        day:           "اليوم",
        totalSleep:    "النوم (ساعات)",
        feedings:      "جلسات الرضاعة",
        totalMlk:      "الحليب (مل)",
        sleepQuality:  "جودة النوم",
        filesTitle:    "الملفات الطبية",
        fileName:      "اسم الملف",
        fileType:      "النوع",
        uploadDate:    "تاريخ الرفع",
        doctorNote:    "هذا التقرير صادر بطلب من الطبيب:",
        male:          "ذكر",
        female:        "أنثى",
        months:        "شهراً",
        years:         "سنوات",
        noData:        "لا توجد بيانات",
        todaySummary:  "ملخص اليوم الحالي",
        todaySleep:    "نوم اليوم",
        todayFeedings: "جلسات الرضاعة",
        todayMilk:     "إجمالي الحليب",
        hours:         "ساعة",
      }
    : {
        title:         "Child Health Report",
        generatedBy:   "Generated by: Journey of Motherhood",
        printDate:     "Report Date:",
        childInfo:     "Child Information",
        name:          "Name",
        birthDate:     "Birth Date",
        age:           "Age",
        gender:        "Gender",
        bloodType:     "Blood Type",
        feeding:       "Feeding Method",
        milestone:     "Developmental Stage",
        growthTitle:   "Growth Records",
        date:          "Date",
        weight:        "Weight (kg)",
        height:        "Height (cm)",
        head:          "Head Circ. (cm)",
        medicalTitle:  "Medical History",
        type:          "Type",
        event:         "Event",
        desc:          "Description",
        sleepTitle:    "Sleep Log (7 days)",
        start:         "Start",
        end:           "End",
        duration:      "Duration",
        quality:       "Quality",
        feedingTitle:  "Feeding Log (30 days)",
        time:          "Time",
        method:        "Method",
        ml:            "Qty (ml)",
        min:           "Duration (min)",
        apptTitle:     "Medical Appointments",
        doctor:        "Doctor",
        apptType:      "Type",
        status:        "Status",
        summaryTitle:  "Daily Summary (last 30 days)",
        day:           "Day",
        totalSleep:    "Sleep (hours)",
        feedings:      "Feedings",
        totalMlk:      "Milk (ml)",
        sleepQuality:  "Sleep Quality",
        filesTitle:    "Medical Files",
        fileName:      "File Name",
        fileType:      "Type",
        uploadDate:    "Upload Date",
        doctorNote:    "This report was requested by Dr.:",
        male:          "Male",
        female:        "Female",
        months:        "months",
        years:         "years",
        noData:        "No data available",
        todaySummary:  "Today's Summary",
        todaySleep:    "Today's Sleep",
        todayFeedings: "Feeding Sessions",
        todayMilk:     "Total Milk",
        hours:         "hours",
      };

  const dir = isAr ? "rtl" : "ltr";
  const font = isAr ? "'Cairo', sans-serif" : "'Poppins', sans-serif";

  // ─── Helpers ───────────────────────────
  const fmt = (d) => d ? new Date(d).toLocaleDateString(isAr ? "ar-SA" : "en-US",
    { year: "numeric", month: "short", day: "numeric" }) : "—";

  const fmtTime = (d) => d ? new Date(d).toLocaleTimeString(isAr ? "ar-SA" : "en-US",
    { hour: "2-digit", minute: "2-digit" }) : "—";

  const calcAge = (birthDate) => {
    if (!birthDate) return "—";
    const birth  = new Date(birthDate);
    const now    = new Date();
    const months = (now.getFullYear() - birth.getFullYear()) * 12 + now.getMonth() - birth.getMonth();
    const years  = Math.floor(months / 12);
    const rem    = months % 12;
    if (isAr) return years > 0 ? `${years} سنة${rem > 0 ? ` و${rem} شهر` : ""}` : `${months} شهراً`;
    return years > 0 ? `${years}y ${rem > 0 ? rem + "mo" : ""}`.trim() : `${months} months`;
  };

  const eventTypeLabel = (type) => ({
    vaccination: isAr ? "تطعيم"   : "Vaccination",
    disease:     isAr ? "مرض"     : "Disease",
    allergy:     isAr ? "حساسية"  : "Allergy",
    checkup:     isAr ? "فحص"     : "Checkup",
    growth:      isAr ? "نمو"     : "Growth",
  }[type] || type);

  const feedingLabel = (type) => ({
    breastfeeding: isAr ? "رضاعة طبيعية" : "Breastfeeding",
    formula:       isAr ? "حليب صناعي"   : "Formula",
    solid_food:    isAr ? "طعام صلب"     : "Solid Food",
  }[type] || type);

  const apptStatusLabel = (s) => ({
    pending:   isAr ? "انتظار"  : "Pending",
    confirmed: isAr ? "مؤكد"   : "Confirmed",
    cancelled: isAr ? "ملغى"   : "Cancelled",
    completed: isAr ? "مكتمل"  : "Completed",
  }[s] || s);

  // ─── Latest growth ───────────────────
  const latestGrowth = growthRecords.length ? growthRecords[growthRecords.length - 1] : null;

  // ─── Daily summary rows ───────────────
  const summaryRows = dailySummary.slice(0, 30).map(s => `
    <tr>
      <td>${fmt(s.date)}</td>
      <td>${s.total_sleep_minutes ? (s.total_sleep_minutes / 60).toFixed(1) : "—"}</td>
      <td>${s.total_feeding_sessions ?? "—"}</td>
      <td>${s.total_milk_ml ?? "—"}</td>
      <td>${s.avg_sleep_quality ?? "—"}</td>
    </tr>`).join("");

  // ─── Growth rows ─────────────────────
  const growthRows = [...growthRecords].reverse().map(r => `
    <tr>
      <td>${fmt(r.recorded_at)}</td>
      <td>${r.weight ?? "—"}</td>
      <td>${r.height ?? "—"}</td>
      <td>${r.head_circumference ?? "—"}</td>
    </tr>`).join("");

  // ─── Medical event rows ───────────────
  const eventRows = medicalEvents.map(ev => `
    <tr>
      <td>${fmt(ev.event_date)}</td>
      <td>${eventTypeLabel(ev.event_type)}</td>
      <td>${ev.title ?? "—"}</td>
      <td>${ev.description ?? "—"}</td>
    </tr>`).join("");

  // ─── Sleep rows ───────────────────────
  const sleepRows = sleepRecords.map(s => {
    const hrs  = Math.floor((s.sleep_duration_minutes || 0) / 60);
    const mins = (s.sleep_duration_minutes || 0) % 60;
    return `
    <tr>
      <td>${fmt(s.sleep_start)}</td>
      <td>${fmtTime(s.sleep_start)}</td>
      <td>${fmtTime(s.sleep_end)}</td>
      <td>${hrs}h ${mins}m</td>
      <td>${s.sleep_quality ?? "—"}</td>
    </tr>`;
  }).join("");

  // ─── Feeding rows ─────────────────────
  const feedingRows = feedingRecords.map(f => `
    <tr>
      <td>${fmt(f.feeding_time)}</td>
      <td>${fmtTime(f.feeding_time)}</td>
      <td>${feedingLabel(f.feeding_type)}</td>
      <td>${f.quantity_ml ?? "—"}</td>
      <td>${f.duration_minutes ?? "—"}</td>
    </tr>`).join("");

  // ─── Appointment rows ─────────────────
  const apptRows = appointments.map(a => `
    <tr>
      <td>${fmt(a.appointment_date)}</td>
      <td>${a.doctor_profiles?.users?.name ?? "—"}</td>
      <td>${a.doctor_profiles?.specialization ?? "—"}</td>
      <td>${a.type ?? "—"}</td>
      <td>${apptStatusLabel(a.status)}</td>
    </tr>`).join("");

  // ─── Files rows ───────────────────────
  const fileRows = medicalFiles.map(f => `
    <tr>
      <td>${f.file_name ?? "—"}</td>
      <td>${f.file_type ?? "—"}</td>
      <td>${fmt(f.uploaded_at)}</td>
      <td>${f.description ?? "—"}</td>
    </tr>`).join("");

  // ─── Today summary boxes ──────────────
  const todayBoxes = healthSummary ? `
    <div class="summary-boxes">
      <div class="sum-box">
        <div class="sum-val">${((healthSummary.total_sleep_minutes || 0) / 60).toFixed(1)}</div>
        <div class="sum-lbl">${t.todaySleep} (${t.hours})</div>
      </div>
      <div class="sum-box">
        <div class="sum-val">${healthSummary.total_feeding_sessions ?? 0}</div>
        <div class="sum-lbl">${t.todayFeedings}</div>
      </div>
      <div class="sum-box">
        <div class="sum-val">${healthSummary.total_milk_ml ?? 0}</div>
        <div class="sum-lbl">${t.todayMilk} (ml)</div>
      </div>
      <div class="sum-box">
        <div class="sum-val">${healthSummary.avg_sleep_quality ?? "—"}</div>
        <div class="sum-lbl">${t.sleepQuality}</div>
      </div>
    </div>` : "";

  // ─── HTML ─────────────────────────────
  const html = `<!DOCTYPE html>
<html lang="${isAr ? "ar" : "en"}" dir="${dir}">
<head>
  <meta charset="UTF-8"/>
  <title>${t.title} — ${child?.name ?? ""}</title>
  <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&family=Poppins:wght@400;600;700&display=swap" rel="stylesheet"/>
  <style>
    *{margin:0;padding:0;box-sizing:border-box;}
    body{font-family:${font};color:#222;background:#fff;font-size:13px;direction:${dir};}
    .page{max-width:900px;margin:0 auto;padding:32px;}
    /* Header */
    .report-header{display:flex;justify-content:space-between;align-items:center;
      border-bottom:3px solid #d68b9d;padding-bottom:16px;margin-bottom:24px;}
    .report-logo{font-size:1.3rem;font-weight:800;color:#d68b9d;font-style:italic;}
    .report-meta{text-align:${isAr ? "left" : "right"};color:#888;font-size:.82rem;}
    .report-meta strong{display:block;font-size:1rem;color:#333;}
    /* Doctor note */
    .doc-note{background:#f0faf4;border:1px solid #2ecc71;border-radius:8px;
      padding:10px 14px;margin-bottom:20px;color:#1a6b5c;font-size:.85rem;font-weight:700;}
    /* Section */
    .section{margin-bottom:28px;}
    .section-title{font-size:1rem;font-weight:800;color:#d68b9d;
      border-bottom:1.5px solid #fdf2f5;padding-bottom:6px;margin-bottom:14px;}
    /* Info grid */
    .info-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;margin-bottom:14px;}
    .info-item{background:#fdf2f5;border-radius:8px;padding:10px 14px;}
    .info-item label{display:block;font-size:.72rem;color:#aaa;font-weight:700;margin-bottom:3px;}
    .info-item span{font-size:.92rem;font-weight:700;color:#333;}
    /* Today summary */
    .summary-boxes{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px;}
    .sum-box{background:#fff8f0;border:1px solid #f0d0a8;border-radius:10px;
      padding:12px;text-align:center;}
    .sum-val{font-size:1.6rem;font-weight:800;color:#e67e22;}
    .sum-lbl{font-size:.72rem;color:#888;font-weight:600;margin-top:3px;}
    /* Table */
    table{width:100%;border-collapse:collapse;font-size:.82rem;margin-bottom:8px;}
    th{background:#d68b9d;color:#fff;padding:8px 10px;font-weight:700;text-align:${isAr ? "right" : "left"};}
    td{padding:7px 10px;border-bottom:1px solid #f0f0f0;color:#444;}
    tr:nth-child(even) td{background:#fafafa;}
    .no-data{color:#bbb;font-size:.85rem;text-align:center;padding:20px;}
    /* Footer */
    .report-footer{margin-top:40px;padding-top:16px;border-top:1px solid #eee;
      text-align:center;color:#bbb;font-size:.75rem;}
    @media print{
      body{font-size:12px;}
      .no-print{display:none!important;}
      .page{padding:16px;}
    }
  </style>
</head>
<body>
<div class="page">

  <!-- Print button (يختفي عند الطباعة) -->
  <div class="no-print" style="margin-bottom:20px;display:flex;gap:10px;">
    <button onclick="window.print()"
      style="background:#d68b9d;color:#fff;border:none;padding:10px 22px;
      border-radius:10px;font-family:inherit;font-weight:700;font-size:.9rem;cursor:pointer;">
      🖨️ ${isAr ? "طباعة التقرير" : "Print Report"}
    </button>
    <button onclick="window.close()"
      style="background:#f4f4f4;color:#888;border:none;padding:10px 22px;
      border-radius:10px;font-family:inherit;font-weight:700;font-size:.9rem;cursor:pointer;">
      ✕ ${isAr ? "إغلاق" : "Close"}
    </button>
  </div>

  <!-- Header -->
  <div class="report-header">
    <div class="report-logo">Journey of Motherhood 🌸</div>
    <div class="report-meta">
      <strong>${t.title}</strong>
      ${t.printDate} ${new Date().toLocaleDateString(isAr ? "ar-SA" : "en-US",
        { year: "numeric", month: "long", day: "numeric" })}
      <br/>${t.generatedBy}
    </div>
  </div>

  ${doctorMode && doctorName ? `<div class="doc-note">⚕️ ${t.doctorNote} ${doctorName}</div>` : ""}

  <!-- Child Info -->
  <div class="section">
    <div class="section-title">👶 ${t.childInfo}</div>
    <div class="info-grid">
      <div class="info-item"><label>${t.name}</label><span>${child?.name ?? "—"}</span></div>
      <div class="info-item"><label>${t.birthDate}</label><span>${fmt(child?.birth_date)}</span></div>
      <div class="info-item"><label>${t.age}</label><span>${calcAge(child?.birth_date)}</span></div>
      <div class="info-item"><label>${t.gender}</label>
        <span>${child?.gender === "male" ? t.male : child?.gender === "female" ? t.female : "—"}</span></div>
      <div class="info-item"><label>${t.bloodType}</label><span>${child?.blood_type ?? "—"}</span></div>
      <div class="info-item"><label>${t.feeding}</label><span>${feedingLabel(child?.feeding_method) || "—"}</span></div>
      ${latestGrowth ? `
      <div class="info-item"><label>${t.weight}</label><span>${latestGrowth.weight ?? "—"} kg</span></div>
      <div class="info-item"><label>${t.height}</label><span>${latestGrowth.height ?? "—"} cm</span></div>
      <div class="info-item"><label>${t.head}</label><span>${latestGrowth.head_circumference ?? "—"} cm</span></div>
      ` : ""}
      ${child?.milestones ? `
      <div class="info-item" style="grid-column:span 3">
        <label>${t.milestone}</label>
        <span>${child.milestones.stage_name} (${child.milestones.min_age_months}–${child.milestones.max_age_months} ${isAr ? "شهر" : "mo"})</span>
      </div>` : ""}
    </div>
  </div>

  <!-- Today Summary -->
  ${healthSummary ? `
  <div class="section">
    <div class="section-title">📊 ${t.todaySummary}</div>
    ${todayBoxes}
  </div>` : ""}

  <!-- Daily Summary Table -->
  ${dailySummary.length ? `
  <div class="section">
    <div class="section-title">📅 ${t.summaryTitle}</div>
    <table>
      <thead><tr>
        <th>${t.day}</th>
        <th>${t.totalSleep}</th>
        <th>${t.feedings}</th>
        <th>${t.totalMlk}</th>
        <th>${t.sleepQuality}</th>
      </tr></thead>
      <tbody>${summaryRows}</tbody>
    </table>
  </div>` : ""}

  <!-- Growth -->
  <div class="section">
    <div class="section-title">📏 ${t.growthTitle}</div>
    ${growthRecords.length ? `
    <table>
      <thead><tr>
        <th>${t.date}</th><th>${t.weight}</th>
        <th>${t.height}</th><th>${t.head}</th>
      </tr></thead>
      <tbody>${growthRows}</tbody>
    </table>` : `<p class="no-data">${t.noData}</p>`}
  </div>

  <!-- Medical Events -->
  <div class="section">
    <div class="section-title">💉 ${t.medicalTitle}</div>
    ${medicalEvents.length ? `
    <table>
      <thead><tr>
        <th>${t.date}</th><th>${t.type}</th>
        <th>${t.event}</th><th>${t.desc}</th>
      </tr></thead>
      <tbody>${eventRows}</tbody>
    </table>` : `<p class="no-data">${t.noData}</p>`}
  </div>

  <!-- Sleep -->
  <div class="section">
    <div class="section-title">🌙 ${t.sleepTitle}</div>
    ${sleepRecords.length ? `
    <table>
      <thead><tr>
        <th>${t.date}</th><th>${t.start}</th>
        <th>${t.end}</th><th>${t.duration}</th><th>${t.quality}</th>
      </tr></thead>
      <tbody>${sleepRows}</tbody>
    </table>` : `<p class="no-data">${t.noData}</p>`}
  </div>

  <!-- Feeding -->
  <div class="section">
    <div class="section-title">🍼 ${t.feedingTitle}</div>
    ${feedingRecords.length ? `
    <table>
      <thead><tr>
        <th>${t.date}</th><th>${t.time}</th>
        <th>${t.method}</th><th>${t.ml}</th><th>${t.min}</th>
      </tr></thead>
      <tbody>${feedingRows}</tbody>
    </table>` : `<p class="no-data">${t.noData}</p>`}
  </div>

  <!-- Appointments -->
  <div class="section">
    <div class="section-title">📋 ${t.apptTitle}</div>
    ${appointments.length ? `
    <table>
      <thead><tr>
        <th>${t.date}</th><th>${t.doctor}</th>
        <th>التخصص</th><th>${t.apptType}</th><th>${t.status}</th>
      </tr></thead>
      <tbody>${apptRows}</tbody>
    </table>` : `<p class="no-data">${t.noData}</p>`}
  </div>

  <!-- Medical Files -->
  ${medicalFiles.length ? `
  <div class="section">
    <div class="section-title">📁 ${t.filesTitle}</div>
    <table>
      <thead><tr>
        <th>${t.fileName}</th><th>${t.fileType}</th>
        <th>${t.uploadDate}</th><th>${isAr ? "الوصف" : "Description"}</th>
      </tr></thead>
      <tbody>${fileRows}</tbody>
    </table>
  </div>` : ""}

  <div class="report-footer">
    Journey of Motherhood © ${new Date().getFullYear()} — ${isAr ? "جميع البيانات سرية وخاصة بالأم" : "All data is confidential and belongs to the mother"}
  </div>
</div>
</body>
</html>`;

  // فتح نافذة طباعة
  const win = window.open("", "_blank", "width=960,height=800");
  win.document.write(html);
  win.document.close();
};