

export const SPECIALIZATIONS = [
  // ─── أمراض النساء والتوليد ───
  { value: "obstetrics_gynecology",    ar: "أمراض النساء والتوليد",    en: "Obstetrics & Gynecology" },
  { value: "gynecology",               ar: "أمراض النساء",             en: "Gynecology" },
  { value: "obstetrics",               ar: "التوليد",                  en: "Obstetrics" },
  { value: "infertility",              ar: "العقم وأطفال الأنابيب",    en: "Infertility & IVF" },
  // ─── طب الأطفال ───
  { value: "pediatrics",               ar: "طب الأطفال",               en: "Pediatrics" },
  { value: "neonatology",              ar: "طب حديثي الولادة",          en: "Neonatology" },
  { value: "pediatric_cardiology",     ar: "قلب الأطفال",              en: "Pediatric Cardiology" },
  { value: "pediatric_neurology",      ar: "أعصاب الأطفال",            en: "Pediatric Neurology" },
  { value: "pediatric_surgery",        ar: "جراحة الأطفال",            en: "Pediatric Surgery" },
  // ─── الصحة النفسية ───
  { value: "psychiatry",               ar: "الطب النفسي",              en: "Psychiatry" },
  { value: "psychology",               ar: "علم النفس الإكلينيكي",     en: "Clinical Psychology" },
  { value: "child_psychiatry",         ar: "الطب النفسي للأطفال",      en: "Child Psychiatry" },
  { value: "postpartum_mental_health", ar: "صحة ما بعد الولادة النفسية", en: "Postpartum Mental Health" },
  // ─── التغذية ───
  { value: "nutrition",                ar: "التغذية العلاجية",          en: "Clinical Nutrition" },
  { value: "pediatric_nutrition",      ar: "تغذية الأطفال والرضع",      en: "Pediatric Nutrition" },
  { value: "maternal_nutrition",       ar: "تغذية الأم والحمل",         en: "Maternal Nutrition" },
  // ─── تخصصات أخرى ───
  { value: "dermatology",              ar: "الأمراض الجلدية",           en: "Dermatology" },
  { value: "endocrinology",            ar: "الغدد الصماء والسكري",      en: "Endocrinology & Diabetes" },
  { value: "general_medicine",         ar: "الطب العام",                en: "General Medicine" },
  { value: "family_medicine",          ar: "طب الأسرة",                 en: "Family Medicine" },
  { value: "lactation_consultant",     ar: "استشاري الرضاعة الطبيعية",  en: "Lactation Consultant" },
  { value: "physiotherapy",            ar: "العلاج الطبيعي",            en: "Physiotherapy" },
  { value: "occupational_therapy",     ar: "العلاج الوظيفي",            en: "Occupational Therapy" },
  { value: "speech_therapy",           ar: "علاج النطق واللغة",          en: "Speech & Language Therapy" },
];

export const ROLE_THEMES = {
  doctor: {
    color: "#7fa9ae",
    light: "#eef6f7",
    titleKey: "doctor.registerTitle",
    subtitleKey: "doctor.registerSubtitle",
    fields: [
      {
        name: "full_name",
        labelKey: "doctor.fullName",
        type: "text",
        icon: "fa-user-md",
        placeholder: "doctor.placeholderFullName",
        instructionKey: "doctor.instructionFullName",
        required: true,
        full: false,
      },
      {
        name: "specialty",
        labelKey: "doctor.specialty",
        type: "select",
        icon: "fa-stethoscope",
        // options سيتم توليدها من SPECIALIZATIONS في الكومبوننت
        instructionKey: "doctor.instructionSpecialty",
        required: true,
        full: false,
      },
      {
        name: "email",
        labelKey: "doctor.email",
        type: "email",
        icon: "fa-envelope",
        placeholder: "doctor.placeholderEmail",
        instructionKey: "doctor.instructionEmail",
        required: true,
        full: false,
      },
      // ── license_number (رقم الترخيص — لا يُعدّل لاحقاً) ──
      {
        name: "license_number",
        labelKey: "doctor.licenseNumber",
        type: "text",
        icon: "fa-id-badge",
        placeholder: "doctor.placeholderLicenseNumber",
        instructionKey: "doctor.instructionLicenseNumber",
        required: true,
        full: false,
      },
      // ── certifications (الشهادات العلمية — قابلة للتعديل) ──
      {
        name: "certifications",
        labelKey: "doctor.certifications",
        type: "text",
        icon: "fa-certificate",
        placeholder: "doctor.placeholderCertifications",
        instructionKey: "doctor.instructionCertifications",
        required: false,
        full: false,
      },
      {
        name: "password",
        labelKey: "auth.password",
        type: "password",
        icon: "fa-lock",
        placeholder: "doctor.placeholderPassword",
        instructionKey: "doctor.instructionPassword",
        required: true,
        full: true,
      },
    ],
  },
  mother: {
    color: "#d68b9d",
    light: "#fdf2f5",
    titleKey: "auth.registerTitle",
    subtitleKey: "auth.registerSubtitle",
    fields: [
      {
        name: "full_name",
        labelKey: "auth.motherName",
        type: "text",
        icon: "fa-user",
        placeholder: "auth.placeholderMotherName",
        instructionKey: "auth.instructionMotherName",
      },
      {
        name: "email",
        labelKey: "auth.email",
        type: "email",
        icon: "fa-envelope",
        placeholder: "auth.placeholderEmail",
        instructionKey: "auth.instructionEmail",
      },
      {
        name: "baby_name",
        labelKey: "auth.babyName",
        type: "text",
        icon: "fa-baby",
        placeholder: "auth.placeholderBabyName",
        instructionKey: "auth.instructionBabyName",
      },
      {
        name: "baby_age",
        labelKey: "auth.babyAge",
        type: "select",
        icon: "fa-calendar-alt",
        options: ["0-3", "3-6", "6-9", "9-12"],
        instructionKey: "auth.instructionBabyAge",
      },
      {
        name: "password",
        labelKey: "auth.password",
        type: "password",
        icon: "fa-lock",
        placeholder: "auth.placeholderPassword",
        instructionKey: "auth.instructionPassword",
        full: true,
      },
    ],
  },

  vendor: {
    color: "#4CAF50",
    light: "#e8f5e9",
    titleKey: "vendor.registerTitle",
    subtitleKey: "vendor.registerSubtitle",
    fields: [
      {
        name: "store_name",
        labelKey: "vendor.storeName",
        type: "text",
        icon: "fa-store",
        placeholder: "vendor.placeholderStoreName",
        instructionKey: "vendor.instructionStoreName",
      },
      {
        name: "email",
        labelKey: "auth.email",
        type: "email",
        icon: "fa-envelope",
        placeholder: "vendor.placeholderEmail",
        instructionKey: "vendor.instructionEmail",
      },
      {
        name: "password",
        labelKey: "auth.password",
        type: "password",
        icon: "fa-lock",
        placeholder: "vendor.placeholderPassword",
        instructionKey: "vendor.instructionPassword",
        full: true,
      },
    ],
  },
};